---
title: "parenting_obs_ling"
author: "Emily"
date: "6/23/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(psych)
library(langcog)
library(ggthemes)
library(lme4)
library(lmerTest)
library(tidytext)
```

# Data preprocessing

Preliminaries.
```{r}
files <- dir("trans_out")

f <- files[1]

for (f in files) {
  jf <- paste("trans_out/",f,sep="")
  tex <- read.table(jf, skip = 19) 

  
  text <-  read.table(jf, header = FALSE, sep = "", quote = "\"'",
           na.strings = "NA",
           skip = 30, 
           strip.white = FALSE, blank.lines.skip = TRUE,
           comment.char = "#",
           allowEscapes = FALSE, flush = FALSE,
           stringsAsFactors = default.stringsAsFactors(),
           fileEncoding = "", encoding = "unknown", text, skipNul = TRUE)
  
  #paq answers
  attitudes_id <- data.frame(sid = as.factor(jd$WorkerId), 
               sent = jd$answers$data$sentence[1:24],
               rating = as.numeric(jd$answers$data$rating[1:24]))
                   
  attitudes <- bind_rows(attitudes, attitudes_id)
}

```

```{r}
library(janeaustenr)
library(dplyr)
library(stringr)

original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",
                                                 ignore_case = TRUE)))) %>%
  ungroup()

original_books
```

