---
title: "Appendix"
output: pdf_document
---

## Experiment 1 Activities

### Video A (6-11.9 months) "Pick it up"

Parents are told to encourage their child to pick up and drop individual objects. They are also encouraged to place toys on a small cloth and show the child that they can drag the cloth towards them to reach the toys. 

Props: cloth, plastic horse, plastic sheep, plastic elephant, toy car

### Video B (6-11.9 months) "Animal sounds"

Parents are told to call different animals and imitate different sounds the animals make. They are also encouraged to observe which animal the child prefers.

Props: plastic sheep, plastic horse, plastic frog, plastic cow, bowls

### Video C (12-17.9 months) "Give me the toy"

Parents are told to ask their child to hand over individual toys. They are also encouraged to praise the child after they give them the toys, and repeat the process until the child could follow the verbal instructions.

Props: toy boat, plastic frog, plastic elephant, toy bus

### Video D (12-17.9 months) "Classifying my toys"

Parents are told to place toys of different sizes (big or small) in two hoops. They are also encouraged to ask their child to distinguish between two objects and identify which one is larger.

Props: two yellow and green rings, big car, small car, big horse, small horse

### Video E (18-23.9 months) "My toys"

Parents are told to show the child toys of the same shape but different sizes, to place one of the objects in a basket and to ask the child to take out the object. They are also encouraged to ask their child if the object is bigger or smaller compared to its pair.

Props: two buckets, big car, small car, big horse, small horse

### Video F (18-23.9 months) "The Orchestra"

Parents are told to give their child a musical instrument to play. They are also encouraged to play a song and see if the child follows the rhythm.

Props: maracas, drum, tambourine, clapper

## Experiment 2 Activities

### Video A (12-17.9 months) "Give me the toy"

Parents are told to ask their child to hand over individual toys. They are also encouraged to praise the child after they give them the toys, and repeat the process until the child could follow the verbal instructions.

Props: plastic pig, plastic horse, plastic dog, plastic cat, plastic cow

### Video B (12-17.9 months) "Classifying my toys"

Parents are told to place toys of different sizes (big or small) in two hoops. They are also encouraged to ask their child to distinguish between two objects and identify which one is larger.

Props: two yellow and green rings, big car, small car, big horse, small horse

### Video C (12-17.9 months) "Geometric shapes jigzsaw puzzle"

Parents are told to encourage their child to name different shapes on a jigzsaw puzzle. Then they are told to undo the puzzle and invite the child to complete the puzzle. 

Props: A jigzsaw puzzle of geometric shapes

### Video D (18-23.9 months) "My toys"

Parents are told to show the child toys of the same shape but different sizes, to place one of the objects in a basket and to ask the child to take out the object. They are also encouraged to ask their child if the object is bigger or smaller compared to its pair.

Props: two buckets, big car, small car, big horse, small horse

### Video E (18-23.9 months) "The Orchestra"

Parents are told to give their child a musical instrument to play. They are also encouraged to play a song and see if the child follows the rhythm.

Props: maracas, drum, tambourine, clapper

### Video F (18-23.9 months) "My Yellow Toys"

Parents are told to show their child yellow toys and to ask, "What color are they?" They are also told to give the child toys of different colors, to ask them to only play with the yellow ones, and to praise the child after they do so.

Props: blue car, yellow car, yellow block, red block, blue block, green block
